apache/maven-compiler-plugin

src/site/apt/index.apt.vm
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
=> (doc) Fixed broken links to scm, issue tracker, and mailing list page.

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
=> Remove extra-check for staleSources is non-null

.github/workflows/maven.yml
=> ci: JDK 15

src/site/apt/examples/compile-using-different-jdk.apt.vm
@elharo You're a native speaker, could you please verify?
=> Grammar on 'Compiling Sources Using A Different JDK' page

.github/pull_request_template.md
=> Fix project key in PR template

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
By looking at the following code, the compiler arguments are passed through unconditionally (whether fork is enabled or not). This change removes the if statement in the Javadoc and adds a note about `-J` options. https://github.com/apache/maven-compiler-plugin/blob/5463357ebc1c65a4e25bfd8ea4c453a618b66bf1/src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java#L918-L957
---
is to use the JIRA issue title in …
=> [MCOMPILER-479] Clarify compiler arguments Javadoc

pom.xml, src/it/default-fork-windows/invoker.properties, src/it/default-fork-windows/pom.xml, src/it/default-fork-windows/src/main/java/MyClass.java, src/it/default-fork-windows/src/test/java/MyTest.java, src/it/default-fork-windows/verify.groovy, src/it/default-fork/invoker.properties, src/it/default-fork/pom.xml, src/it/default-fork/src/main/java/MyClass.java, src/it/default-fork/src/test/java/MyTest.java, src/it/default-fork/verify.groovy, src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java, src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java, src/main/java/org/apache/maven/plugin/compiler/TestCompilerMojo.java
=> [MCOMPILER-225] javac.sh/javac.bat added to archive

pom.xml
=> use plexus-compiler 2.10.0

src/it/MCOMPILER-500-package-info-incr/invoker.properties, src/it/MCOMPILER-500-package-info-incr/pom.xml, src/it/MCOMPILER-500-package-info-incr/src/main/java/dummy/Person.java, src/it/MCOMPILER-500-package-info-incr/src/main/java/dummy/foo/Person.java, src/it/MCOMPILER-500-package-info-incr/src/main/java/dummy/package-info.java, src/it/MCOMPILER-500-package-info-incr/verify.groovy, src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java, src/main/java/org/apache/maven/plugin/compiler/TestCompilerMojo.java
=> [MCOMPILER-500] add some parameter to pattern from stale source calculation

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
- Display recompilation causes
- apply changes from #129
To make …
=> MCOMPILER 499 display recompilation causes

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
=> [MCOMPILER-457] Change showWarnings to true by default

pom.xml
* 3.4.0 brings in support for building on JDK 19
* once the parent brings in this version, the explicit version can be of course removed
[Individual Contributor License …
=> [MCOMPILER-519] Upgrade maven-invoker-plugin from 3.3.0 to 3.4.0

pom.xml, src/it/MCOMPILER-522-unresolvable-dependency/invoker.properties, src/it/MCOMPILER-522-unresolvable-dependency/pom.xml, src/it/MCOMPILER-522-unresolvable-dependency/src/main/java/org/apache.maven.plugins.compiler.it/SimpleAnnotation.java, src/it/MCOMPILER-522-unresolvable-dependency/src/main/java/org/apache.maven.plugins.compiler.it/SimpleObject.java, src/it/MCOMPILER-522-unresolvable-dependency/verify.groovy, src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
* heavily based on work by @cstamas (PR #151)
* added IT to verify the build fails if one the dependencies cannot be resolved (e.g. does not exist)
[Individual Contributor License …
=> [MCOMPILER-522] Use maven-resolver to resolve 'annotationProcessorPaths' dependencies

.asf.yaml
Trivial change to make the JIRA numbers "clickable".
To make clear …
=> asf.yaml: autolink MCOMPILER JIRAs

src/it/MCOMPILER-275_separate-moduleinfo/src/main/java/module-info.java
=> [MCOMPILER-526] Fix IT

pom.xml
=> [MCOMPILER-527] Upgrade plexus-java to 1.1.2

src/it/MCOMPILER-366/pom.xml, src/it/MCOMPILER-366/verify.groovy, src/it/automodules-application/pom.xml, src/it/automodules-application/verify.groovy, src/it/automodules-library/pom.xml, src/it/automodules-library/verify.groovy, src/it/automodules-transitive-module/pom.xml, src/it/automodules-transitive-module/verify.groovy
Closes reported. by Dependabot alert related to https://github.com/advisories/GHSA-8vhq-qq4p-grq3
=> Update plexus-utils to 3.0.24 - in its

src/it/mcompiler-120/pom.xml
=> (doc) Drop unused and vulnerable dependency to log4j

src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java
=> [MCOMPILER-547]: Initialize pathElements to empty

src/site/site.xml, src/site/xdoc/download.xml.vm
=> [MCOMPILER-552] Refresh download page

pom.xml
=> [MCOMPILER-554] Update plexus-java to 1.2.0

src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java
JIRA issue: https://issues.apache.org/jira/browse/MCOMPILER-559
=> [MCOMPILER-559] Warn if overwriting the project's artifact's file to a different value

src/site/apt/examples/pass-compiler-arguments.apt.vm
=> subject verb agreement

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
This is no longer evaluated in plexus-compiler-javac (https://github.com/codehaus-plexus/plexus-compiler/issues/356). It was never used by any other plexus compilers in the past.
[Individual Contributor …
=> [MCOMPILER-576] Deprecate parameter "compilerVersion"

src/it/MCOMPILER-170/invoker.properties, src/it/MCOMPILER-275_separate-moduleinfo/invoker.properties, src/it/MCOMPILER-298/invoker.properties, src/it/MCOMPILER-525/pom.xml, src/it/mcompiler-120/invoker.properties, src/it/multirelease-patterns/multimodule/multirelease/pom.xml, src/it/multirelease-patterns/multimodule/pom.xml, src/it/multirelease-patterns/multiproject/multirelease-base/pom.xml, src/it/multirelease-patterns/multiproject/pom.xml, src/it/multirelease-patterns/packaging-plugin/pom.xml, src/it/multirelease-patterns/singleproject-runtime/invoker.properties, src/it/multirelease-patterns/singleproject-runtime/pom.xml, src/it/multirelease-patterns/singleproject-toolchains/invoker.properties, src/it/multirelease-patterns/singleproject-toolchains/pom.xml, src/it/non-english-warnings/pom.xml, src/it/setup_annotation-verify-plugin/pom.xml, src/it/setup_jar_automodule/pom.xml
https://issues.apache.org/jira/browse/MCOMPILER-585
=> [MCOMPILER-585] Refresh plugins versions in ITs

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
https://issues.apache.org/jira/browse/MCOMPILER-574
=> [MCOMPILER-574] Propagate cause of exception in AbstractCompilerMojo

Jenkinsfile, pom.xml, src/it/MCOMPILER-522-unresolvable-dependency/verify.groovy
- **Build with Maven 4**
- **Fix build with Maven 4.0.0-beta-3**
=> Fix build with Maven 4

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
Replaces #260
This makes code more clear and error prone but also improves performance a little bit. …
=> Refactoring: AbstractCompilerMojo: Replace StringBuilder with String.join()

.github/workflows/pr-automation.yml
=> Add PR automation

.github/release-drafter-3.x.yml, .github/workflows/release-drafter.yml
=> Update release-drafter configuration

.github/workflows/maven-verify.yml
=> Use default Maven versions for build on GitHub

.github/workflows/release-drafter.yml
=> Fix release-drafter config

pom.xml
=> Update scm tag according to branch
