apache/maven-compiler-plugin

src/it/jpms_compile-main-empty-test-bar/invoker.properties
src/it/jpms_compile-main-empty-test-bar/pom.xml
src/it/jpms_compile-main-empty-test-bar/src/test/java/bar/BarTests.java
src/it/jpms_compile-main-empty-test-bar/src/test/java/module-info.java
src/it/jpms_compile-main-empty-test-bar/verify.groovy
src/it/jpms_compile-main-foo-test-bar/invoker.properties
src/it/jpms_compile-main-foo-test-bar/pom.xml
src/it/jpms_compile-main-foo-test-bar/src/main/java/foo/Foo.java
src/it/jpms_compile-main-foo-test-bar/src/main/java/module-info.java
src/it/jpms_compile-main-foo-test-bar/src/test/java/bar/BarTests.java
src/it/jpms_compile-main-foo-test-bar/src/test/java/module-info.java
src/it/jpms_compile-main-foo-test-bar/verify.groovy
src/it/jpms_compile-main-foo-test-foo/invoker.properties
src/it/jpms_compile-main-foo-test-foo/pom.xml
src/it/jpms_compile-main-foo-test-foo/src/main/java/foo/Foo.java
src/it/jpms_compile-main-foo-test-foo/src/main/java/module-info.java
src/it/jpms_compile-main-foo-test-foo/src/test/java/foo/FooTests.java
src/it/jpms_compile-main-foo-test-foo/src/test/java/module-info.java
src/it/jpms_compile-main-foo-test-foo/verify.groovy
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
src/main/java/org/apache/maven/plugin/compiler/TestCompilerMojo.java
src/test/java/org/apache/maven/plugin/compiler/CompilerMojoTestCase.java

Prior to this commit module descriptors `module-info.java` were not compiled by the TestCompilerMojo. This commit introduces support for test sources organized with module descriptors.
See motivation: https://twitter.com/rfscholte/status/927132319374331904
Supersedes: https://github.com/apache/maven-plugins/pull/139

[MCOMPILER-341] Compile module descriptors with TestCompilerMojo

---

src/it/MCOMPILER-349_dependencyChanged/dependent-module/pom.xml
src/it/MCOMPILER-349_dependencyChanged/dependent-module/src/main/java/Main.java
src/it/MCOMPILER-349_dependencyChanged/invoker.properties
src/it/MCOMPILER-349_dependencyChanged/pom.xml
src/it/MCOMPILER-349_dependencyChanged/service/pom.xml
src/it/MCOMPILER-349_dependencyChanged/service/src/main/java/TestService.java
src/it/MCOMPILER-349_dependencyChanged/verify.groovy
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

Issue description:
Module doesn't recompile when its dependency is changed and `mvn compile` is runned (without `clean`)
Reason: Bug in changed dependency detection mechanism 
Default fileExtensions contained '.class', while FileUtils#getExtension( method used in AbstractCompilerMojo#hasNewFile returns file extension without '.' (e.g. 'class')
is to use the JIRA issue title in the pull request title and in the first line of the …

[MCOMPILER-349] - changed dependency detection.

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

This is a resubmission of PR apache/maven-plugins#126.
I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).

[MCOMPILER-306] Fix `compilerArgs` example usage

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java
src/main/java/org/apache/maven/plugin/compiler/TestCompilerMojo.java
src/test/java/org/apache/maven/plugin/compiler/CompilerMojoTestCase.java
src/test/java/org/apache/maven/plugin/compiler/stubs/CompilerManagerStub.java
src/test/java/org/apache/maven/plugin/compiler/stubs/CompilerStub.java

These were the result of running the IntelliJ linter and picking the juiciest looking changes.
Hopefully there's nothing too contentious here - see individual commits for details.
Addresses
- MCOMPILER-382
- MCOMPILER-383
- MCOMPILER-384
- MCOMPILER-385

Miscellaneous code cleanups

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

This is maybe a bit rude, piggy-backing on an old Jira ticket but it didn't seem to quite warrant a new one.
Correct a tiny error in the documentation and simplify the code around handling the default set of file extensions to monitor for timestamp changes during incremental compilation.

MCOMPILER-349 cleanups

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

Use the `isEmpty()` convenience method more, as we do elsewhere.

(doc) Use !isEmpty() instead of size() > 0

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

Make better use of `isDebugEnabled()`. See individual commits for details.
The diff looks better if you ignore whitespace changes.

Cleanup debug log handling

---

src/main/java/org/apache/maven/plugin/compiler/CompilationFailureException.java

This class can be a little bit more concise.
The nullity check in `longMessage()` is made redundant by the lack of an equivalent check in `shortMessage`. `CompilationFailureException` is thrown in two places in `AbstractCompilerMojo` and both of those are guaranteed to pass a non-null object.
Whilst we're in here, remove a redundant local variable in `shortMessage()` and merge the `StringBuilder` calls onto a single line.

(doc) Simplify CompilationFailureException

---

src/main/java/org/apache/maven/plugin/compiler/TestCompilerMojo.java

be performed on your pull request automatically. - I expect you to have a CI setup (e.g. travis)
To make clear that you …

MCOMPILER-359 - Fix for NPE

---

src/site/apt/examples/set-compiler-release.apt.vm
src/site/apt/examples/set-compiler-source-and-target.apt.vm
src/site/apt/index.apt.vm
src/site/site.xml

(doc) Add example on using --release javac option

---

src/site/apt/multirelease.apt

(Previous faillure due to missing env var `JAVA_HOME` expected in https://github.com/apache/maven-compiler-plugin/blob/1455594a943791fa14f7a733dbcf48b648100a8d/src/test/java/org/apache/maven/plugin/compiler/CompilerMojoTestCase.java#L213)
I also ran `mvn site -DskipTests=true` to observe my changes in produced `target/site/multirelease.html`.
---
To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) you have to acknowledge this by using the following check-box.

(doc) Fixes in multirelease page

---

src/it/mcompiler-21_class-remove/pom.xml

The comment in the POM wrongly describes the tested scenario. I guess this was due to a copy and paste from another IT, https://github.com/apache/maven-compiler-plugin/blob/master/src/it/mcompiler-21_methodname-change/pom.xml
If your pull request is about ~20 lines of code you don't …

Fixed the comment in the POM

---

pom.xml
src/it/MCOMPILER-481-requires-static-included/app/pom.xml
src/it/MCOMPILER-481-requires-static-included/app/src/main/java/module-info.java
src/it/MCOMPILER-481-requires-static-included/app/src/main/java/org/test/app/Main.java
src/it/MCOMPILER-481-requires-static-included/app/src/test/java/org/test/app/MainTest.java
src/it/MCOMPILER-481-requires-static-included/invoker.properties
src/it/MCOMPILER-481-requires-static-included/pom.xml
src/it/MCOMPILER-481-requires-static-included/service/pom.xml
src/it/MCOMPILER-481-requires-static-included/service/src/main/java/module-info.java
src/it/MCOMPILER-481-requires-static-included/service/src/main/java/org/test/service/JSONService.java
src/it/MCOMPILER-481-requires-static-included/service/src/main/java/org/test/service/Service.java
src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java
src/main/java/org/apache/maven/plugin/compiler/TestCompilerMojo.java

[MCOMPILER-481] compiler plugin should include static module for compilation

---

src/it/MCOMPILER-474_recompile-dependent-when-package/dependent-module/pom.xml
src/it/MCOMPILER-474_recompile-dependent-when-package/dependent-module/src/main/java/Main.java
src/it/MCOMPILER-474_recompile-dependent-when-package/invoker.properties
src/it/MCOMPILER-474_recompile-dependent-when-package/pom.xml
src/it/MCOMPILER-474_recompile-dependent-when-package/service/pom.xml
src/it/MCOMPILER-474_recompile-dependent-when-package/service/src/main/java/TestService.java
src/it/MCOMPILER-474_recompile-dependent-when-package/verify.groovy
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

https://issues.apache.org/jira/browse/MCOMPILER-474
If a dependency module has changed since last compilation and we run `mvn package` then dependent module doesn't get recompiled, because dependency is added to its `compilePath` as a `.jar` file, not as a `classes` directory.
This PR changes the logic in the `isDependencyChanged()` method so that it also checks jar files for modifications.
The integration test is mostly a copy of `MCOMPILER-349_dependencyChanged`, with a few tweaks.
where you replace …

[MCOMPILER-474] - Also check jar files when determining if dependencies changed

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

| before | after |
|---|---|
| ![mcp-tc-m](https://user-images.githubusercontent.com/11896137/152641433-51b54ac5-058e-4d37-86f1-276e15ab6531.png) | ![mcp-tc-pr](https://user-images.githubusercontent.com/11896137/152641441-9594e621-8469-4714-932b-33f1eaabda85.png) |

(doc) Fix typo and follow xml block style used for other parameters

---

.github/workflows/maven-verify.yml

add more jdk for testing

---

src/it/MCOMPILER-485/invoker.properties
src/it/MCOMPILER-485/pom.xml
src/it/MCOMPILER-485/src/main/java/dummy/HelloWorld.java
src/it/MCOMPILER-485/src/main/java/dummy/package-info.java
src/it/MCOMPILER-485/verify.groovy
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

https://issues.apache.org/jira/browse/MCOMPILER-485
[Per JVMS 4.2.1](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.2.1), the package name representation in the internal class structure always contains forward slashes in place of periods.  This PR fixes the code from MCOMPILER-205 which passed a package name extracted from the file path which used backward slashes on Windows.
While not necessarily a cause of the bug, the [javadocs for `ClassVisitor`](https://asm.ow2.io/javadoc/org/objectweb/asm/ClassVisitor.html) (the superclass of `ClassWriter`) state "The methods of this class must be called in the following order: visit visitSource ..." so I reordered those method calls as well.
The IT is copied from MCOMPILER-205 but with a more detailed test to confirm the …

[MCOMPILER-485] Fixes internal string format in generated package-info.class

---

pom.xml
src/it/MCOMPILER-346/invoker.properties
src/it/MCOMPILER-346/pom.xml
src/it/MCOMPILER-346/src/main/java/org/jenkinsci/test/acceptance/server/PooledJenkinsController.java
src/it/MCOMPILER-346/verify.groovy

- [MCOMPILER-346] use plexus-compiler snapshot to avoid jdk bug add an it for it
- use released of plexus-compilers
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if …

MCOMPILER 346 workaround to jdk bug: assertion error from javaxcompiler javax.tools API

---

pom.xml
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

[MCOMPILER-426] add flag to enable-preview java compiler feature

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java
src/main/java/org/apache/maven/plugin/compiler/TestCompilerMojo.java

Fixes [MCOMPILER-347: Includes and excludes not passed into CompilerConfiguration](https://issues.apache.org/jira/browse/MCOMPILER-347)

[MCOMPILER-347] Set Xcludes in config passed to actual compiler

---

pom.xml
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
src/test/java/org/apache/maven/plugin/compiler/CompilerMojoTestCase.java
src/test/resources/unit/compiler-implicit-test/plugin-config-none.xml
src/test/resources/unit/compiler-implicit-test/plugin-config-not-set.xml

Needs
- https://github.com/codehaus-plexus/plexus-compiler/pull/202
or similar.
- [MCOMPILER-488](https://issues.apache.org/jira/browse/MCOMPILER-488)

[MCOMPILER-488] dedicated option for `implicit` javac flag

---

src/it/MCOMPILER-495/invoker.properties
src/it/MCOMPILER-495/pom.xml
src/it/MCOMPILER-495/src/main/java/dummy/package-info.java
src/it/MCOMPILER-495/verify.groovy
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

In `createMissingPackageInfoClasses` if the `target` directory does not contain the parent path of a `package-info.class` file create the directories before attempting to write the `package-info.class file`
the [Apache …

MCOMPILER-495 -  Fixes missing dirs in createMissingPackageInfoClasses

---

.github/workflows/maven-verify.yml
src/it/MCOMPILER-349_dependencyChanged/pom.xml
src/it/MCOMPILER-474_recompile-dependent-when-package/pom.xml
src/it/mcompiler-182/pom.xml
src/it/mcompiler-21_class-remove/pom.xml
src/it/mcompiler-21_methodname-change/pom.xml

test build with 18 

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
src/main/java/org/apache/maven/plugin/compiler/TestCompilerMojo.java

usage of reflection is not needed anymore

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
src/site/apt/index.apt.vm

https://issues.apache.org/jira/browse/MCOMPILER-505
To make clear …

[MCOMPILER-505] - Update default source/target from 1.7 to 1.8

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

[MCOMPILER-457] Warn about warn-config conflicting values

---

src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java

JIRA: https://issues.apache.org/jira/browse/MCOMPILER-501
When using multi-release JARs, the way is to configure the plugin, see https://github.com/apache/maven-compiler-plugin/blob/master/src/it/multirelease-patterns/singleproject-runtime/pom.xml#L92-L111
This causes a warning because the parameter is set as read-only.

[MCOMPILER-501] compileSourceRoots parameter should be writable 

---

pom.xml
src/it/MCOMPILER-192/verify.groovy
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
src/test/java/org/apache/maven/plugin/compiler/stubs/CompilerStub.java

https://issues.apache.org/jira/browse/MCOMPILER-516

[MCOMPILER-516] upgrade plexus-compiler to improve compiling message

---

.github/workflows/maven-verify.yml
src/it/MCOMPILER-481-requires-static-included/pom.xml

[MCOMPILER-523] Test with Maven 3.9.0 and fix the failing IT

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

Use this link to re-run the recipe: https://public.moderne.io/recipes/org.openrewrite.java.migrate.apache.commons.lang.IsNotEmptyToJdk?organizationId=QXBhY2hlIE1hdmVu

[MNG-6829] Replace StringUtils#isEmpty(String) & #isNotEmpty(String)

---

src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-api/pom.xml
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-api/src/main/java/mcompiler391/SimpleAnnotation.java
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-processor-dep-v1/pom.xml
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-processor-dep-v1/src/main/java/mcompiler391/AnnotationProcessorDependencyV1.java
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-processor-dep-v2/pom.xml
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-processor-dep-v2/src/main/java/mcompiler391/AnnotationProcessorDependencyV2.java
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-processor/pom.xml
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-processor/src/main/java/mcompiler391/SimpleAnnotationProcessor.java
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user1/pom.xml
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user1/src/main/java/mcompiler391/SimpleObject1.java
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user1/src/test/java/mcompiler391/SimpleTestObject1.java
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user2/pom.xml
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user2/src/main/java/mcompiler391/SimpleObject2.java
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user2/src/test/java/mcompiler391/SimpleTestObject2.java
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user3/pom.xml
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user3/src/main/java/mcompiler391/SimpleObject3.java
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user3/src/test/java/mcompiler391/SimpleTestObject3.java
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user4/pom.xml
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user4/src/main/java/mcompiler391/SimpleObject4.java
src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user4/src/test/java/mcompiler391/SimpleTestObject4.java
src/it/MCOMPILER-391-processorpath-dep-mgmt/invoker.properties
src/it/MCOMPILER-391-processorpath-dep-mgmt/pom.xml
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

* dependency managemet can be used for two slighty difference use
cases (when it comes to annotation processors):
-- getting the version of the top-level processor path elements
-- passing the list of managed dependencies to maven-resolver
when resolving the whole processorpath
These two can be combined, so there is total of 4 valid combinations
(some of them make more sense than the others, but generally there is
no reason to not support all of them)
* using dependency management when resolving transitive dependencies of
annotation processors is something that may or may not be desired.
For that reason, there is a new flag that explicitly enables this
behavior, while default is to _not_ use dependency management
(the current behavior)
* do not be scared by the the number of new lines. …

[MCOMPILER-391] Use dep mgmt when resolving annotation processors and their deps

---

src/site/apt/examples/module-info.apt.vm

In 2023 assume everyone is on 3.3.1 or later.

Remove references to old Maven versions.

---

src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java

Currently simply all kind of items are added to the classpath leading to strange errors in the ECJ compiler plugin because it does not know how to handle pom or other possible types.
This adds an additional check to see if the artifact handler actually claims the itme should be put on the classpath,
be performed on your pull …

[MCOMPILER-544] don't add items to classpath that are not used for that

---

src/it/MCOMPILER-500-package-info-incr/verify.groovy
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

[MCOMPILER-549] Improve log message in case of recompilation

---

pom.xml
src/test/java/org/apache/maven/plugin/compiler/CompilerMojoTestCase.java

[MCOMPILER-551] Upgrade Parent to 40

---

src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java
src/main/java/org/apache/maven/plugin/compiler/TestCompilerMojo.java

- add more documentation when and how to use it (and when to not use it)
- fixes MCOMPILER-550
please …

[MCOMPILER-550] make outputDirectory writable

---

src/main/java/org/apache/maven/plugin/compiler/TestCompilerMojo.java

JIRA: https://issues.apache.org/jira/browse/MCOMPILER-558
Projects should be able to configure the `compileSourceRoots` also in the `testCompile` goal (like in the `compile` goal)
This causes a warning because the parameter is set as read-only.

[MCOMPILER-558] compileSourceRoots in testCompile should be writable

---

src/it/MCOMPILER-542/invoker.properties
src/it/MCOMPILER-542/pom.xml
src/it/MCOMPILER-542/src/main/java/module-info.java
src/it/MCOMPILER-542/src/main/java/org/maven/test/Main.java
src/it/MCOMPILER-542/verify.groovy
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java
src/main/java/org/apache/maven/plugin/compiler/ModuleInfoTransformer.java

pulling in other changes. https://issues.apache.org/jira/browse/MCOMPILER-542
To make clear …

[MCOMPILER-542] Clean JDK patch version in module-info.class 

---

src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java

Currently, the CompilerMojo relies on the `outputDirectory` parameter without allowing external configuration (e.g via commandline). This limits the flexibility of the plugin in certain build environments.
The source code for the CompilerMojo has been modified to introduce a new property, `maven.compiler.outputDirectory`, which can be configured externally. This change will enable users to specify a custom output directory for the compiler, offering greater flexibility and customization in different build scenarios while retaining backward compatibility with the existing `outputDirectory` parameter.

[MCOMPILER-562] Add property maven.compiler.outputDirectory to CompilerMojo

---

src/it/mcompiler-106/pom.xml
src/it/mcompiler-106/verify.groovy
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

https://issues.apache.org/jira/browse/MCOMPILER-565

[MCOMPILER-565] Allow project build by Maven 4

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

Clarify meaning in javadoc
To make clear that you license your …

[MCOMPILER-577] Rename parameter "forceJavacCompilerUse"

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

Turns out this is just a documentation issue. `full` works fine but is
not documented.
Following this checklist to help us incorporate your
for the change (usually before you start working on it).  Trivial changes like typos do not
require a JIRA issue.  Your pull request should address just this issue, without
is to use the JIRA issue title in the pull request title and in the first line of the
please ask on the …

[MCOMPILER-548] JDK 21 throws annotations processing warning that can not be turned off

---

src/it/release-without-profile-fork/invoker.properties
src/it/release-without-profile-fork/pom.xml
src/it/release-without-profile-fork/src/main/java/MyClass.java
src/it/release-without-profile-fork/verify.groovy
src/it/release-without-profile/invoker.properties
src/it/release-without-profile/pom.xml
src/it/release-without-profile/src/main/java/MyClass.java
src/it/release-without-profile/verify.groovy
src/site/apt/examples/set-compiler-release.apt.vm

https://issues.apache.org/jira/browse/MCOMPILER-582

[MCOMPILER-582] Automatic detection of release option for JDK < 9

---

src/site/apt/non-javac-compilers.apt.vm

https://issues.apache.org/jira/browse/MCOMPILER-584

[MCOMPILER-584] Refresh page - Using Non-Javac Compilers

---

src/site/apt/index.apt.vm

Java 1.8 is now minimum, not Java 1.6.

Remove info about old versions

---

pom.xml
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
src/main/java/org/apache/maven/plugin/compiler/TestCompilerMojo.java
src/test/java/org/apache/maven/plugin/compiler/TestCompilerMojoTest.java

https://issues.apache.org/jira/browse/MCOMPILER-591

[MCOMPILER-591] testCompile - fix detections of target less than 1.9

---

src/site/apt/usage.apt.vm

Also we don't need generic info on this page that applies to all plugins rather than the maven-compiler-plugin specifically

Remove Maven 3 note

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
src/main/java/org/apache/maven/plugin/compiler/CompilationFailureException.java

No need to call System.getProperty with magic names 'path.separator' and 'line.separator'. Java does that for us and provides friendly methods/fields for them.

Cleanup usages of System.getProperty calls.

---

.github/workflows/maven-verify.yml
pom.xml
src/it/MCOMPILER-346/verify.groovy

* Upgrade to Maven 4.0.0-rc-2 and testing 4.0.0-beta-3.
* Revert "Temporarily disable the MCOMPILER-346 integration test".
* Remove version properties for dependencies that are not used anymore.

Upgrade to Maven 4.0.0-rc-2.

---

pom.xml

In parent, we use bom for JUnit, so some of the artifacts can be in incompatibility version

Use JUnit version from parent

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

It is a new parameter added in #271

Rename property `moduleVersion` to `maven.compiler.moduleVersion`

---

pom.xml
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java

Allow module-version configuration (like in master branch).
To …

[MCOMPILER-579] allow module-version configuration

---

src/site/apt/examples/set-compiler-release.apt.vm
src/site/apt/examples/set-compiler-source-and-target.apt.vm
src/site/apt/index.apt.vm
src/site/site.xml

This PR updates several parts of the documentation to Maven 4 based on JDK 17 and aligns the docs to the new Java version schema. In particular on the front page it's mentioned that "8" is the default, where in the code it's actual "1.8" - but I wanted to keep docs consistent here.
Note: For Maven 3 branch I will create a separate PR later (maybe starting this evening)

Update docs for Maven 4 and release option

---

src/it/MCOMPILER-538/code/MyAnnotatedClass.bad.java
src/it/MCOMPILER-538/code/MyAnnotatedClass.good.java
src/it/MCOMPILER-538/code/pom.xml
src/it/MCOMPILER-538/code/src/main/java/bar/.gitignore
src/it/MCOMPILER-538/code/src/main/java/bar/package-info.java
src/it/MCOMPILER-538/invoker.properties
src/it/MCOMPILER-538/pom.xml
src/it/MCOMPILER-538/processor/pom.xml
src/it/MCOMPILER-538/processor/src/main/java/foo/MyAnnotation.java
src/it/MCOMPILER-538/processor/src/main/java/foo/MyProcessor.java
src/it/MCOMPILER-538/processor/src/main/resources/META-INF/services/javax.annotation.processing.Processor
src/it/setup_annotation-verify-plugin/src/main/java/org.apache.maven.plugins.compiler.it/SourcePathReadGoal.java
src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java

Fix for [MCOMPILER-538](https://issues.apache.org/jira/browse/MCOMPILER-538).
The `generatedSourcesPath` will still be added to the *maven* project paths.
---
[Individual Contributor License …

[MCOMPILER-538] Do not add target/generated-sources/annotations to the source roots

---

pom.xml
src/test/java/org/apache/maven/plugin/compiler/CompilerMojoTestCase.java
src/test/java/org/apache/maven/plugin/compiler/stubs/CompilerStub.java

This is in replacement of #315 generated by dependabot. Upgrading the `maven-plugins` dependency is more work than just upgrading the version number, because:
* New errors are raised by Checkstyle.
* The `maven-dependency-plugin` is now executed (inherited from a new block in `maven-plugins`), and that execution fails if we do not delete the output files generated by the stub compiler. This is because those output files are not real `*.class` files.

Bump org.apache.maven.plugins:maven-plugins from 43 to 44

---

src/it/GH-331-no-module-version/invoker.properties
src/it/GH-331-no-module-version/pom.xml
src/it/GH-331-no-module-version/src/main/java/com/foo/MyClass.java
src/it/GH-331-no-module-version/src/main/java/module-info.java
src/it/GH-331-no-module-version/verify.groovy
src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java

Allow to not use --module-version for the Java compiler

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
src/main/java/org/apache/maven/plugin/compiler/DeltaList.java

This pull request targets the 3.x branch as I think this support has been rewritten in 4.
Here is the situation prior to this patch with a massive project (~40k source files):
> 7172 samples, 3.79%
The first commit keeps the ordering as is and make sure we write the file sorted and the outputs of `DeltaList` are sorted.
The behavior is exactly the same as before.
Here is the situation after the first commit:
> 78 samples, 0.04% - basically, the only thing left is the tiny thing you can see at the far right of the previous flame graph.
The second commit is a further optimization, which might not be useful and only sorts when displaying the output. The file is written unsorted.
It doesn't change much tbh so we might as well not include the second commit.
I did the work to be comprehensive …

Improve DeltaList behavior for large projects

---

src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
src/site/markdown/examples/annotation-processor.md
src/site/markdown/examples/annotationprocessor.md
src/site/site.xml

Since JDK 23 no annotation processing is done by default for security reason.
This PR adds information about this and also adds an example page how to do it in general and what is the recommended way to execute annotation processing (which applies also to earlier JDK versions).

Add JDK 23 information and example for annotation processing

---

.github/workflows/maven-verify.yml
pom.xml
src/main/java/org/apache/maven/plugin/compiler/DependencyCoordinate.java
src/main/java/org/apache/maven/plugin/compiler/SourceDirectory.java
src/test/java/org/apache/maven/plugin/compiler/CompilerMojoTestCase.java

Trivial changes so that the plugin builds against maven 4.0.0-rc-4

Port to maven 4.0.0-rc-4

---

pom.xml

After the mvn verify, the dependency plugin was pointing these guys as undeclared and used. This should fix it.

Undeclared dependencies

---

src/it/MCOMPILER-567-kt/pom.xml

By default, it starts a daemon, but uses IT local repo, hence m-clean-p fails on Windows.
Kotlin was upped here: 52d922f9215fe52de51853d3635cbbc91b56f68a
Ref: https://kotlinlang.org/docs/kotlin-daemon.html

Fix for new Kotlin
